#!/usr/bin/env bash
set -euo pipefail

_PROMPT="󱕴"
_SELECTION="${1:-}"

_DATA_SECRET=""
_DATA_MODE=""

_check_dependencies() {
  if ! command -v gopass &>/dev/null; then
    printf "required command not found: gopass\n"
    exit 1
  fi
}

_notify() {
  local _msg="${1:-}"
  if [ -n "${_msg}" ]; then
    notify-send -i password Passmenu "${_msg}"
  fi
}

_parse_data() {
  if [ -n "${ROFI_DATA:-}" ]; then
    local _data_key=""
    local _data_value=""

    local IFS=','
    for data in ${ROFI_DATA}; do
      _data_key="${data%%=*}"
      _data_value="${data#*=}"

      case "${_data_key}" in
      secret)
        _DATA_SECRET="${_data_value}"
        ;;
      esac
    done
  fi
}

_print_options() {
  # NOTE: If secret is selected, show mode options
  if [ -z "${_DATA_SECRET}" ]; then
    gopass ls --flat
  elif [ -z "${_DATA_MODE}" ]; then
    printf "Password\nOTP\nLogin"
  fi
}

_parse_selection() {
  if printf "Password\nOTP\nLogin" | grep -q "${_SELECTION}"; then
    _DATA_MODE="${_SELECTION}"
  else
    _DATA_SECRET="${_SELECTION}"
    printf "\0data\x1f%ssecret=%s\n" "${ROFI_DATA:+${ROFI_DATA},}" "${_DATA_SECRET}"
  fi

  if [ -n "${_DATA_SECRET}" ] && [ -n "${_DATA_MODE}" ]; then
    case "${_DATA_MODE}" in
    Password)
      (printf "%s" "$(gopass show -o "${_DATA_SECRET}")" | wl-copy) &
      _notify "Copied password for ${_DATA_SECRET} to clipboard"
      ;;
    OTP)
      (printf "%s" "$(gopass otp "${_DATA_SECRET}")" | wl-copy) &
      _notify "Copied OTP for ${_DATA_SECRET} to clipboard"
      ;;
    Login)
      (gopass show "${_DATA_SECRET}" | awk '/(email|user|username):/ {printf "%s", $2; exit}' | wl-copy) &
      _notify "Copied Login for ${_DATA_SECRET} to clipboard"
      ;;
    esac
  fi
}

_main() {
  printf "\0prompt\x1f%s\n" "${_PROMPT}"
  printf "\0no-custom\x1ftrue\n"

  _parse_data
  if [ -n "${_SELECTION}" ]; then
    _parse_selection
  fi
  _print_options
}

_check_dependencies
_main "${@}"
