icons:
  doas: 󰒘
  sudoedit: 󱆠
  nvim: 
  chezmoi: 
  terraform: 󱁢
  lazygit: 󰊢
  man: 󰈙
  buildah: 
  flatpak: 󰏗
  cat: 󰦨
  bat: 󰦨
  devbox: 
  task: 
  watch: 󰈈
  ssh: 
  ffmpeg: 󱜀
  ttyper: 󰌌
  find: 
