#!/usr/bin/env bash
set -euo pipefail

__SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
export GNUPGHOME="${HOME}/.local/share/gnupg"

if ! command -v gopass &>/dev/null; then
  printf "required command not found: gopass\n"
  exit 1
fi

password="$(gopass ls --flat | rofi -dmenu -p gopass -theme "${__SCRIPT_DIR}/style.rasi")"

if [[ "${password}" =~ ^otp/.* ]]; then
  gopass otp -c "${password}" 2>/dev/null
else
  gopass show -c "${password}" 2>/dev/null
fi
